### PR TITLE
fixed overflow issue for x86 archs

### LINKED ISSUE #7: Constant math.MaxUint32 overflows int on x86 arch
When building for a x86 architecture the math.MaxUint32 will overflow int since MaxUint32 is not type declared it will be set to int. If you don't want to support a x86 architecture you can close this.

### PR DESCRIPTION
**Pull request by Pirayya**
fixes #7 

Not the most sexy fix but will take two memory slots on x86 and the conversion in 64bit arch int to uint64 should not overflow

### CODE REVIEW

File: encoder.go [hunk 1]
```diff
@@ -98,7 +98,7 @@ func (kse *keyStoreEncoder) writeCertificate(cert *Certificate) error {
 		return err
 	}
 	certLen := len(cert.Content)
```
Comment (pavel-v-chernykh) [inline encoder.go]: I think wrapping `uint64(len(cert.Content))` would be enough.
Could you fix it and I'll merge it then.

File: encoder.go [hunk 2]
```diff
@@ -150,7 +150,7 @@ func (kse *keyStoreEncoder) writePrivateKeyEntry(alias string, pke *PrivateKeyEn
 		return err
 	}
 	privKeyLen := len(encodedPrivKeyContent)
```
Comment (pavel-v-chernykh) [inline encoder.go]: Same as above.

File: encoder.go [hunk 3]
```diff
@@ -162,7 +162,7 @@ func (kse *keyStoreEncoder) writePrivateKeyEntry(alias string, pke *PrivateKeyEn
 		return err
 	}
 	certCount := len(pke.CertChain)
```
Comment (pavel-v-chernykh) [inline encoder.go]: Same as above

**Comment by Pirayya** [comment]
Thanks @pavel-v-chernykh for the quick check! Much sexier fix :smile:, I updated the branch with a new commit which should be more satisfactory!

**Comment by pavel-v-chernykh** [comment]
@Pirayya , thanks for your contributions.
